<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_DE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube fetchmail_rc plugin                    |
 | Copyright (C) 2016, Kay Strobach                                      |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kay Strobach <github@kay-strobach.de>                         |
 +-----------------------------------------------------------------------+
 @version 1.0.0
*/

$labels = array();
$labels['accounts'] = 'POP/IMAP Mailkonten';
$labels['manageaccounts'] = 'Mailkonten verwalten';
$labels['newAddress'] = 'Mailkonto hinzufügen';

$labels['reception_server'] = 'Serveradresse';

$labels['add_edit_account'] = 'Mailkonto hinzufügen / bearbeiten';
$labels['noaccounts'] = 'Keine Mailkonten';
$labels['disabled'] = 'Deaktiviert';

$labels['mail_host'] = 'Mailserver';
$labels['mail_ssl'] = 'SSL verwenden';
$labels['mail_username'] = 'Benutzername';
$labels['mail_password'] = 'Passwort';
$labels['mail_arguments'] = 'Argumente';
$labels['mail_protocol'] = 'Protokol';
$labels['mail_disabled'] = 'Deaktiviert';

$labels['new_account_saved'] = 'Neues Mailkonto gespeichert';
$labels['account_updated'] = 'Mailkonto erfolgreich aktualisiert';
$labels['save_error'] = 'Es gab ein Problem beim Speichern des Mailkontos';
$labels['delete_success'] = 'Mailkonto erfolgreich gelöscht';
$labels['delete_error'] = 'Es gab ein Problem beim Löschen des Mailkontos';

$labels['configuration'] = 'Konfiguration';
$labels['accountstatus'] = 'Mailkontostatus';
$labels['lastimport'] = 'Letzte erfolgreiche Verbindung';
$labels['status'] = 'Status';
$labels['testaccount'] = 'Test Mailkonto';
$labels['forceretrieve'] = 'Erzwinge das abholen von Nachrichten';


$labels['errorlabel'] = 'Es ist ein Fehler aufgetreten';
$labels['please_wait'] = 'Bitte warten, diese Aktion kann einen Moment dauern';
$labels['nbconsecutiveserrors'] = 'Anzahl der Fehler';
$labels['status_successful'] = 'Erfolgreich importiert';

$labels['error_during_process'] = 'Es gab einen Fehler beim Importieren';
$labels['retrieve_account_success'] = 'Das Mailkonto wurde ohne Fehler importiert';
$labels['test_account_success'] = 'Der Test mit dem Testaccount wurde ohne Fehler durchgeführt.';

$labels['notalreadyautoimported'] = 'Der automatische Import ist noch nicht ausgeführt worden';
$labels['fill_server_address'] = 'Bitte Mailserver ausfüllen';
$labels['fill_username'] = 'Bitte Benutzername ausfüllen';


$labels['authenticaction_error'] = 'Authentifizierungsfehler';
$labels['error_during_user_retrieving'] = 'Es gab ein Problem beim holen der Benutzerdaten aus der Datenbank';

$labels['short_mail_error'] = 'errors';
