<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_US/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube fetchmail_rc plugin                    |
 | Copyright (C) 2012, Iabsis                                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Gilles Hemmerlé <giloux@gmail.com>                            |
 +-----------------------------------------------------------------------+
 @version 1.0.0
*/

$labels = array();
$labels['accounts'] = 'POP/IMAP accounts';
$labels['manageaccounts'] = 'Manage accounts to import';
$labels['newAddress'] = 'Add a new account';

$labels['reception_server'] = 'Server address';

$labels['add_edit_account'] = 'Add/Edit account';
$labels['noaccounts'] = 'No accounts';
$labels['disabled'] = 'Disabled';

$labels['mail_host'] = 'Mail host';
$labels['mail_ssl'] = 'Use ssl';
$labels['mail_username'] = 'Username';
$labels['mail_password'] = 'Password';
$labels['mail_arguments'] = 'Arguments';
$labels['mail_protocol'] = 'Protocol';
$labels['mail_disabled'] = 'Disabled';

$labels['new_account_saved'] = 'New account saved';
$labels['account_updated'] = 'Account has correctly been updated';
$labels['save_error'] = 'Error occurred during saving process';
$labels['delete_success'] = 'Deleted successfully';
$labels['delete_error'] = 'An error occured during deletion process';

$labels['configuration'] = 'Configuration';
$labels['accountstatus'] = 'Account status';
$labels['lastimport'] = 'Last successfully import';
$labels['status'] = 'Status';
$labels['testaccount'] = 'Test account';
$labels['forceretrieve'] = 'Force messages retrieving';


$labels['errorlabel'] = 'Error occured';
$labels['please_wait'] = 'Please wait, this operation can take some time';
$labels['nbconsecutiveserrors'] = 'Consecutives errors count';
$labels['status_successful'] = 'Successfully imported';

$labels['error_during_process'] = 'An error occurred during import process';
$labels['retrieve_account_success'] = 'The account retriving completed without any errors';
$labels['test_account_success'] = 'The account test has ran without any errors. Account seems to work.';

$labels['notalreadyautoimported'] = 'The auto import has not been launched yet';
$labels['fill_server_address'] = 'Thanks to set the mail host';
$labels['fill_username'] = 'Thanks to set the username';


$labels['authenticaction_error'] = 'Authentication error';
$labels['error_during_user_retrieving'] = 'Error during the user datas retrieving from the database';