<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fr_FR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube fetchmail_rc plugin                    |
 | Copyright (C) 2012, Iabsis                                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Gilles Hemmerlé <giloux@gmail.com>                            |
 +-----------------------------------------------------------------------+
 @version 1.0.0
*/

$labels = array();
$labels['accounts'] = 'Comptes POP/IMAP';
$labels['manageaccounts'] = 'Gestion des comptes à importer';
$labels['newAddress'] = 'Ajouter un nouveau compte';

$labels['reception_server'] = 'Serveur de réception';

$labels['add_edit_account'] = 'Ajout/Edition d\'un compte';
$labels['noaccounts'] = 'Aucun compte';
$labels['disabled'] = 'désactivé';

$labels['mail_host'] = 'Serveur de mail';
$labels['mail_ssl'] = 'Utiliser ssl';
$labels['mail_username'] = 'Nom d\'utilisateur';
$labels['mail_password'] = 'Mot de passe';
$labels['mail_arguments'] = 'Arguments';
$labels['mail_protocol'] = 'Protocole';
$labels['mail_disabled'] = 'Désactivé';

$labels['new_account_saved'] = 'Le nouveau compte a bien été créé';
$labels['account_updated'] = 'Le compte a bien été mis à jour';
$labels['save_error'] = 'Une erreur s\'est produite pendant la sauvegarde';
$labels['delete_success'] = 'La suppression s\'est effectué avec succès';
$labels['delete_error'] = 'Un problème est survenue pendant la suppression du compte';

$labels['configuration'] = 'Configuration';
$labels['accountstatus'] = 'Statut du compte';
$labels['lastimport'] = 'Date de dernier import réussi';
$labels['status'] = 'Statut';
$labels['testaccount'] = 'Tester le compte';
$labels['forceretrieve'] = 'Forcer la récupération des messages';


$labels['errorlabel'] = 'Erreur survenue';
$labels['please_wait'] = 'Merci de patienter, cette opération peut prendre quelques secondes';
$labels['nbconsecutiveserrors'] = 'Nombre d\'erreurs successives';
$labels['status_successful'] = 'L\'import s\'est déroulé avec succès';

$labels['error_during_process'] = 'Une erreur s\'est produite pendant le processus';
$labels['retrieve_account_success'] = 'La récupération du compte s\'est effectuée avec succès';
$labels['test_account_success'] = 'Le compte a été testé et fonctionne correctement';

$labels['notalreadyautoimported'] = 'L\'import automatique ne s\'est pas encore executé';
$labels['fill_server_address'] = 'Merci de saisir une adresse serveur';
$labels['fill_username'] = 'Merci de saisir un nom d\'utilisateur';

$labels['authenticaction_error'] = 'Erreur d\'authentification';
$labels['error_during_user_retrieving'] = 'Une erreur s\'est produite pendant la récupération de l\'utilisateur dans la base de données';

