<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pl_PL.inc                                                |
 |                                                                       |
 | Language file of the Roundcube fetchmail_rc plugin                    |
 | Copyright (C) 2012, Iabsis                                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: maślak                                                        |
 +-----------------------------------------------------------------------+
 @version 1.0.0
	Tłumaczenie by maślak ;) 06.05.2013
*/

$labels = array();
$labels['accounts'] = 'Konta POP/IMAP';
$labels['manageaccounts'] = 'Zarządzaj kontami do importu';
$labels['newAddress'] = 'Dodaj nowe konto';

$labels['reception_server'] = 'Adres serwera';

$labels['add_edit_account'] = 'Dodaj/zmień konto';
$labels['noaccounts'] = 'Brak kont';
$labels['disabled'] = 'Wyłączone';

$labels['mail_host'] = 'Adres serwera';
$labels['mail_ssl'] = 'Używaj ssl';
$labels['mail_username'] = 'Użytkownik';
$labels['mail_password'] = 'Hasło';
$labels['mail_arguments'] = 'Argumenty';
$labels['mail_protocol'] = 'Protokół';
$labels['mail_disabled'] = 'Wyłącz';

$labels['new_account_saved'] = 'Nowe konto zapisane';
$labels['account_updated'] = 'Knto zostało pomyśnie zaktualizowane';
$labels['save_error'] = 'Wystąpił błąd podczas zapisu konfiguracji';
$labels['delete_success'] = 'Konto pomyślie usunięte';
$labels['delete_error'] = 'Wystąpił błąd podczas usuwania konta';

$labels['configuration'] = 'Konfiguracja';
$labels['accountstatus'] = 'Status konta';
$labels['lastimport'] = 'Ostatni pomyślny import';
$labels['status'] = 'Status';
$labels['testaccount'] = 'Przetestuj ustawienia';
$labels['forceretrieve'] = 'Wymuś pobranie wiadomości';


$labels['errorlabel'] = 'Wystąpił błąd';
$labels['please_wait'] = 'Proszę czekać, ta operacja może chwię potrwać';
$labels['nbconsecutiveserrors'] = 'Liczba powtarzających się błędów';
$labels['status_successful'] = 'Operacja zakończyła się sukcesem!';

$labels['error_during_process'] = 'Wystąpił błąd podczas importu';
$labels['retrieve_account_success'] = 'Pobieranie z konta zewnętrzenego zakończone sukcesem';
$labels['test_account_success'] = 'Test konta zakończony powodzeniem. Wygląda na to że wszystko działa prawidłowo';

$labels['notalreadyautoimported'] = 'Automatyczny import nie został jeszcze uruchomiony';
$labels['fill_server_address'] = 'Musisz podać adres serwera';
$labels['fill_username'] = 'Musisz podać nazwę użytkownika';


$labels['authenticaction_error'] = 'Błąd logowania';
$labels['error_during_user_retrieving'] = 'Błąd podczas pobierania ustawień z bazy danych';

$labels['short_mail_error'] = 'błędy';
