<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube fetchmail_rc plugin                    |
 | Copyright (C) 2012, Iabsis                                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: vanchester <admin@vanchester.ru>                              |
 +-----------------------------------------------------------------------+
 @version 1.0.0
*/

$labels = array();
$labels['accounts'] = 'Аккаунты POP/IMAP';
$labels['manageaccounts'] = 'Управление аккаунтами для сбора почты с других почтовых серверов';
$labels['newAddress'] = 'Добавить новый аккаунт';

$labels['reception_server'] = 'Адрес сервера';

$labels['add_edit_account'] = 'Добавить/Изменить аккаунт';
$labels['noaccounts'] = 'Нет аккаунтов';
$labels['disabled'] = 'Отключен';

$labels['mail_host'] = 'POP/IMAP сервер';
$labels['mail_ssl'] = 'Использовать SSL';
$labels['mail_username'] = 'Логин';
$labels['mail_password'] = 'Пароль';
$labels['mail_arguments'] = 'Аргументы';
$labels['mail_protocol'] = 'Протокол';
$labels['mail_disabled'] = 'Отключен';

$labels['new_account_saved'] = 'Новый аккаунт сохранен';
$labels['account_updated'] = 'Аккаунт успешно обновлен';
$labels['save_error'] = 'При сохранении произошла ошибка';
$labels['delete_success'] = 'Успешно удален';
$labels['delete_error'] = 'При удалении произошла ошибка';

$labels['configuration'] = 'Конфигурация';
$labels['accountstatus'] = 'Статус';
$labels['lastimport'] = 'Последняя успешная доставка';
$labels['status'] = 'Статус';
$labels['testaccount'] = 'Проверить аккаунт';
$labels['forceretrieve'] = 'Доставить почту вручную';


$labels['errorlabel'] = 'Произошла ошибка';
$labels['please_wait'] = 'Пожалуйста, подождите. Операция может занять некоторое время';
$labels['nbconsecutiveserrors'] = 'Количество повторных ошибок';
$labels['status_successful'] = 'Операция успешно завершена';

$labels['error_during_process'] = 'При доставке произошла ошибка';
$labels['retrieve_account_success'] = 'Доставка успешно завершена';
$labels['test_account_success'] = 'Проверка аккаунта успешно завершена. Доставка для него должна работать корректно.';

$labels['notalreadyautoimported'] = 'Автоматическая доставка еще не выполнялась';
$labels['fill_server_address'] = 'Вы должны указать адрес сервера';
$labels['fill_username'] = 'Вы должны ввести имя пользователя';


$labels['authenticaction_error'] = 'Ошибка авторизации';
$labels['error_during_user_retrieving'] = 'При получении данных пользователя из БД произошла ошибка';

$labels['short_mail_error'] = 'ошибки';
